# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
format =  '''
\$ $username $directory $git_branch $fill $git_state $git_status $nodejs $lua $docker_context $memory_usage
'''
add_newline = true

[fill]
symbol = 'â”€'

[username]
style_user = 'blue bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_status]
conflicted = 'ğŸ³'
ahead = 'â¬†ï¸ ${count} '
behind = 'â¬‡ï¸ ${count} '
diverged = 'â†•ï¸ â¬†ï¸ {ahead_count} â¬‡ï¸ ${behind_count} '
up_to_date = 'âœ“ '
untracked = 'ğŸ¤· '
stashed = 'ğŸ“¦ '
modified = 'âœï¸ '
staged = '[++\($count\)](green) '
renamed = 'ğŸ’± '
deleted = 'ğŸ—‘ '

[memory_usage]
disabled = false
threshold = 70
symbol = 'ğŸ§  '
style = 'bold dimmed red'

[docker_context]
format = '[ ğŸ‹ $context ](blue bold)'

[nodejs]
format = '[ $symbol($version )]($style)' 

[lua]
format = '[ $symbol($version )]($style)'
